from __future__ import annotations

from typing import Any, Callable


class _Signal:
    def connect(self, slot: Callable[..., Any]) -> None: ...


class Qt:
    class Key:
        Key_Left: int
        Key_Right: int

    class WindowModality:
        NonModal: int
        ApplicationModal: int

    class WindowType:
        Window: int
        WindowStaysOnTopHint: int

    class Orientation:
        Horizontal: int
        Vertical: int


class QPoint:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def x(self) -> int: ...
    def y(self) -> int: ...


class QRect:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def x(self) -> int: ...
    def y(self) -> int: ...
    def width(self) -> int: ...
    def height(self) -> int: ...
    def top(self) -> int: ...
    def center(self) -> QPoint: ...
    def topLeft(self) -> QPoint: ...


class _Screen:
    def availableGeometry(self) -> QRect: ...


class QApplication:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    @staticmethod
    def topLevelWidgets() -> list[Any]: ...
    @staticmethod
    def primaryScreen() -> _Screen: ...


class QWidget:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def removeAction(self, *args: Any, **kwargs: Any) -> None: ...
    def setLayout(self, *args: Any, **kwargs: Any) -> None: ...
    def setMinimumHeight(self, *args: Any, **kwargs: Any) -> None: ...
    def setMinimumWidth(self, *args: Any, **kwargs: Any) -> None: ...
    def setMinimumSize(self, *args: Any, **kwargs: Any) -> None: ...
    def setWindowTitle(self, *args: Any, **kwargs: Any) -> None: ...
    def setWindowModality(self, *args: Any, **kwargs: Any) -> None: ...
    def setWindowFlags(self, *args: Any, **kwargs: Any) -> None: ...
    def setGeometry(self, *args: Any, **kwargs: Any) -> None: ...
    def setFixedSize(self, *args: Any, **kwargs: Any) -> None: ...
    def setModal(self, *args: Any, **kwargs: Any) -> None: ...
    def setSizeGripEnabled(self, *args: Any, **kwargs: Any) -> None: ...
    def setStyleSheet(self, *args: Any, **kwargs: Any) -> None: ...
    def resize(self, *args: Any, **kwargs: Any) -> None: ...
    def move(self, *args: Any, **kwargs: Any) -> None: ...
    def mapToGlobal(self, *args: Any, **kwargs: Any) -> QPoint: ...
    def rect(self) -> QRect: ...
    def width(self) -> int: ...
    def height(self) -> int: ...
    def raise_(self) -> None: ...
    def activateWindow(self) -> None: ...
    def show(self) -> None: ...
    def setFocus(self) -> None: ...


class QDialog(QWidget):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def exec(self) -> int: ...
    def accept(self) -> None: ...
    def reject(self) -> None: ...


class QMenuBar(QWidget):
    def addMenu(self, *args: Any, **kwargs: Any) -> QMenu: ...
    def actions(self) -> list[QAction]: ...


class QAction:
    triggered: _Signal
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def menu(self) -> QMenu | None: ...
    def text(self) -> str: ...
    def setShortcut(self, *args: Any, **kwargs: Any) -> None: ...
    def setToolTip(self, *args: Any, **kwargs: Any) -> None: ...
    def setCheckable(self, *args: Any, **kwargs: Any) -> None: ...
    def setChecked(self, *args: Any, **kwargs: Any) -> None: ...


class QMenu(QWidget):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def addAction(self, *args: Any, **kwargs: Any) -> Any: ...
    def addMenu(self, *args: Any, **kwargs: Any) -> QMenu: ...
    def addSeparator(self) -> None: ...
    def actions(self) -> list[QAction]: ...
    def title(self) -> str: ...


class QInputDialog:
    @staticmethod
    def getText(*args: Any, **kwargs: Any) -> tuple[str, bool]: ...


class QDialogButtonBox(QWidget):
    class StandardButton:
        Ok: int
        Cancel: int

    accepted: _Signal
    rejected: _Signal
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def button(self, *args: Any, **kwargs: Any) -> QPushButton: ...


class QVBoxLayout:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def addWidget(self, *args: Any, **kwargs: Any) -> None: ...
    def addLayout(self, *args: Any, **kwargs: Any) -> None: ...
    def addStretch(self, *args: Any, **kwargs: Any) -> None: ...
    def setSpacing(self, *args: Any, **kwargs: Any) -> None: ...
    def setContentsMargins(self, *args: Any, **kwargs: Any) -> None: ...


class QHBoxLayout:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def addWidget(self, *args: Any, **kwargs: Any) -> None: ...
    def addLayout(self, *args: Any, **kwargs: Any) -> None: ...
    def addStretch(self, *args: Any, **kwargs: Any) -> None: ...
    def setSpacing(self, *args: Any, **kwargs: Any) -> None: ...
    def setContentsMargins(self, *args: Any, **kwargs: Any) -> None: ...


class QGridLayout:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def addWidget(self, *args: Any, **kwargs: Any) -> None: ...
    def addLayout(self, *args: Any, **kwargs: Any) -> None: ...
    def setHorizontalSpacing(self, *args: Any, **kwargs: Any) -> None: ...
    def setVerticalSpacing(self, *args: Any, **kwargs: Any) -> None: ...
    def setColumnStretch(self, *args: Any, **kwargs: Any) -> None: ...


class QFormLayout:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def addRow(self, *args: Any, **kwargs: Any) -> None: ...


class QGroupBox(QWidget):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...


class QLabel(QWidget):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def setText(self, *args: Any, **kwargs: Any) -> None: ...
    def setWordWrap(self, *args: Any, **kwargs: Any) -> None: ...


class QPushButton(QWidget):
    clicked: _Signal
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def setEnabled(self, *args: Any, **kwargs: Any) -> None: ...
    def setText(self, *args: Any, **kwargs: Any) -> None: ...


class QTextEdit(QWidget):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def setPlainText(self, *args: Any, **kwargs: Any) -> None: ...
    def toPlainText(self) -> str: ...


class QTextBrowser(QWidget):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def setOpenExternalLinks(self, *args: Any, **kwargs: Any) -> None: ...
    def setMarkdown(self, *args: Any, **kwargs: Any) -> None: ...
    def setPlainText(self, *args: Any, **kwargs: Any) -> None: ...
    def setHtml(self, *args: Any, **kwargs: Any) -> None: ...


class QSplitter(QWidget):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def addWidget(self, *args: Any, **kwargs: Any) -> None: ...
    def setSizes(self, *args: Any, **kwargs: Any) -> None: ...


class QScrollArea(QWidget):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def setWidgetResizable(self, *args: Any, **kwargs: Any) -> None: ...
    def setWidget(self, *args: Any, **kwargs: Any) -> None: ...


class QPlainTextEdit(QWidget):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def setPlaceholderText(self, *args: Any, **kwargs: Any) -> None: ...
    def toPlainText(self) -> str: ...


class QLineEdit(QWidget):
    textChanged: _Signal
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def setText(self, *args: Any, **kwargs: Any) -> None: ...
    def text(self) -> str: ...
    def setPlaceholderText(self, *args: Any, **kwargs: Any) -> None: ...


class QCheckBox(QWidget):
    stateChanged: _Signal
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def isChecked(self) -> bool: ...
    def setChecked(self, *args: Any, **kwargs: Any) -> None: ...


class QRadioButton(QWidget):
    toggled: _Signal
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def isChecked(self) -> bool: ...
    def setChecked(self, *args: Any, **kwargs: Any) -> None: ...


class QButtonGroup:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def addButton(self, *args: Any, **kwargs: Any) -> None: ...
    def setExclusive(self, *args: Any, **kwargs: Any) -> None: ...


class QComboBox(QWidget):
    textActivated: _Signal
    currentTextChanged: _Signal
    activated: _Signal
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def addItems(self, *args: Any, **kwargs: Any) -> None: ...
    def currentIndex(self) -> int: ...
    def setCurrentIndex(self, *args: Any, **kwargs: Any) -> None: ...


class QKeySequence:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...


class QShortcut:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
