from typing import Any

def qconnect(*args: Any, **kwargs: Any) -> Any: ...
def showInfo(*args: Any, **kwargs: Any) -> Any: ...
def showText(*args: Any, **kwargs: Any) -> Any: ...
def showWarning(*args: Any, **kwargs: Any) -> Any: ...
def tooltip(*args: Any, **kwargs: Any) -> Any: ...
